### PR TITLE
pygbag ci for wasm wheel

### PR DESCRIPTION
**Pull request by pmp-p**
nb: remember to sync from pygbag main before merging unsure what could happen otherwise.

what differs :
 `raylib physac raygui` are not pinned and use git latest 

=> that way if something upstream breaks it may show up quick in CI

what is not done yet by order of increasing difficulty:
 - ~~remove the multiple python builds in yaml since the module is abi3 ok ( i need to do change yml for  that upstream anyway so almost done )~~
 - whl is not automatically set into release. see https://github.com/pygame-web/python-wasm-sdk/blob/66fd3b811f24d385bf2cde6285fb7c36cb0c5722/.github/workflows/ci.yml#L53
 - python files are not yet into static filesystem for quick testing from project pages, so it would still actually access the published wheel.
 - wasi/osmesa testing.
 - vendor/readme and documentation. :D

it's fast <2min ! https://github.com/pmp-p/pygbag-vendor/actions/runs/8131568714

### CODE REVIEW

**Comment by pmp-p** [comment]
re, i see that the wheel was created https://github.com/electronstudio/pygbag-raylib/actions/runs/8155545702/job/22291288108#step:4:293 :)

Could you activate the issues on the repo ?  To see how to automate  testing/publishing, the pygbag repo does not produce any wheel for now so it is not relevant there.

**Comment by electronstudio** [comment]
@pmp-p ok

**Comment by electronstudio** [comment]
@pmp-p I have got the wheel     `raylib-5.0.0.1-cp310-abi3-wasm32_bi_emscripten.whl` from https://github.com/electronstudio/pygbag-raylib/actions/runs/8191675556 .  How do I test if it works?

**Comment by pmp-p** [comment]
use same way you did for the examples list https://electronstudio.github.io/raylib-python-cffi-pygbag-examples/,  just unzip the wheel next to the main.py  and remove the "raylib" from PEP block it will re-pack the wheel with the sample and  force a local load after relaunching pygbag main.py

**Comment by electronstudio** [comment]
ok, that works.  What do I do when I want to publish a release?  Send the wheel to you?  Upload the wheel to pypy?

**Comment by pmp-p** [comment]
pypi does not accept any wasm wheel yet. 

There is a hack to use it to provide wasm wheels but it may has side effects :
eg on https://pypi.org/project/raylib/#files if there was a `py3-none-any.whl` like there https://pypi.org/project/raypyc/#files 
pygbag, pyodide and pyscript would install it
and pygbag would be able to load it.

meanwhile the simplest would probably be "publish a github release" ( I'll try to add something to vendor script to can do that automatically) and drop a note on https://github.com/pygame-web/pkg-porting-wasm/issues/34


ref:
https://discuss.python.org/t/support-wasm-wheels-on-pypi/21924/8

https://github.com/python/cpython/issues/96426#issuecomment-1271144421

**Pull request merged**
